### PR TITLE
Graphs Implementation

### LINKED ISSUE #1: Add more solutions
You can add more solutions to any new problems. **Make sure the solution(s) is/are in Java language.**

### PR DESCRIPTION
**Pull request by 21RachitShukla**
Fixed #1

### CODE REVIEW

**Comment by Kvaibhav01** [comment]
Can you please add the problem's question/title?

**Comment by 21RachitShukla** [comment]
It is not a problem specific code, includes implementation of graphs and functions related to it.

**Comment by Kvaibhav01** [comment]
@21RachitShukla this repo only contains problems from Hackerrank. If this problem is there, then kindly add a Hackerrank problem link in the comment. Else, your PR will not be merged. Hope you understand. 😀

**Comment by 21RachitShukla** [comment]
https://www.hackerrank.com/challenges/dijkstrashortreach/problem
https://www.hackerrank.com/challenges/bfsshortreach/problem
https://www.hackerrank.com/topics/bipartite-matching

These are some of the problems/topics for which the above code works.

**Pull request merged**
